Update checks workflow

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -14,10 +14,12 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Run nano
-        shell: bash {0}
+        shell: bash
         run: |
+          nano --version
+
           echo "include \"$(pwd)/*.nanorc\"" > ~/.nanorc
-          echo "test" | nano 2> log.txt || grep "^Error" log.txt && exit 1 || exit 0
+          echo "" | nano 2> log.txt || grep "^Error" log.txt && exit 1 || exit 0
 
 #       - name: Parse nanorc files
 #         run: |
